name: cade_meu_carro
description: Never lose your car in a parking lot again!
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/parking.png"
  image_path_android: "assets/launcher/parking.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/icon_marker.png
    - assets/images/bg.jpg
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
        - asset: fonts/IBMPlexSans-Bold.ttf
        - asset: fonts/IBMPlexSans-Light.ttf
        - asset: fonts/IBMPlexSans-Medium.ttf
        - asset: fonts/IBMPlexSans-SemiBold.ttf
